/**
 * Generates docs/index.html from docs/index.template.html by inlining the
 * docs IIFE bundle (dist/docs/ns.iife.js, built from src/docs.ts, which
 * exposes the useNs factory as window.useNs), producing a fully self-contained
 * demo page that can be opened directly in a browser — no server, no adjacent JS.
 *
 * Run via: bun run build:docs (builds the IIFE bundle first).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const templatePath = resolve(root, 'docs/index.template.html')
const bundlePath = resolve(root, 'dist/docs/ns.iife.js')
const outputPath = resolve(root, 'docs/index.html')

const marker = '<script src="ns.iife.js"></script>'

const template = readFileSync(templatePath, 'utf8')
if (!template.includes(marker)) {
	console.error(`build-docs: marker not found in ${templatePath}: ${marker}`)
	process.exit(1)
}

let bundle: string
try {
	bundle = readFileSync(bundlePath, 'utf8')
} catch {
	console.error(
		`build-docs: bundle not found at ${bundlePath} — run "bun run build:docs"`
	)
	process.exit(1)
}

// Prevent the inlined JS from terminating the <script> element early.
const safeBundle = bundle.replace(/<\/script/gi, '<\\/script')

const banner = `<!-- Generated by scripts/build-docs.ts — do not edit. Edit docs/index.template.html instead. -->\n`
const html = banner + template.replace(marker, `<script>\n${safeBundle}\n</script>`)

writeFileSync(outputPath, html)
console.log(
	`build-docs: wrote ${outputPath} (${(html.length / 1024).toFixed(1)} kB, bundle inlined)`
)
