name: CI General (non-persistent)

on:
  push:
    branches-ignore:
      - production
      - test
  pull_request:
    branches-ignore:
      - production
      - test

jobs:
  call-test-non-persistent:
    name: Running Test (non-persistent)
    uses: './.github/workflows/reusable.test.yml'
    with:
      persistent: false
  
  call-lint-non-persistent:
    needs: call-test-non-persistent
    name: Running Linting (non-persistent)
    uses: './.github/workflows/reusable.lint.yml'
    with:
      run-linting: true
  
  call-build-non-persistent:
    needs: call-lint-non-persistent
    name: Running build (non-persistent)
    uses: './.github/workflows/reusable.build.yml'
    with:
      persistent: false