name: CI General (non-persistent)

on:
  push:
    branches-ignore:
      - production
      - test
  pull_request:
    branches-ignore:
      - production
      - test

jobs:
  general-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test (non-persistent)
        uses: './.github/workflows/reusable.test.yml'
        with:
          persistent: false
      
      - name: Lint (non-persistent)
        uses: './.github/workflows/reusable.lint.yml'
        with:
          run-linting: true
      
      - name: Build (non-persistent)
        uses: './.github/workflows/reusable.build.yml'
        with:
          persistent: false