name: CI General (non-persistent)

on:
  push:
    branches:
      - '**' # Trigger on all branches
    branches-ignore:
      - production
      - test
  pull_request:
    branches:
      - '**' # Trigger on all branches
    branches-ignore:
      - production
      - test

jobs:
  call-reusable--test:
    uses: './.github/workflows/reusable/test.yml'
    with:
      persistent: false
  call-reusable--lint:
    uses: './.github/workflows/reusable/lint.yml'
  call-reusable--build:
    uses: './.github/workflows/reusable/build.yml'
    with: 
      persistent: false