name: CI Production

on:
  pull_request:
    branches: [ production ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checking out the repository with the latest version
      - uses: actions/checkout@v4
        with:
          ref: production

      # Setting up the latest Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      # Setting up the latest Bun.js version
      - name: Set up Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      # Configuring git for GitHub Actions
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch production

      # Installing dependencies using Bun
      - name: Install Dependencies
        run: bun install

      # Running build using Bun
      - name: Run Build
        run: bun run build
  
      # Committing build artifacts to the production branch
      - name: Commit Build
        run: |
         git add .
         git commit -m "GitHub Actions: Persist build artifacts[ci skip]" || echo "No changes to commit"
         git push origin production
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Running Vitest with coverage using Bun
      - name: Run Vitest with Coverage
        run: bunx vitest run --coverage

      # Uploading coverage to Coveralls
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

      # Publishing to NPM
      - name: Publish to NPM
        run: bunx npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}