name: CI Production & Publish

on:
  push:
    branches: [ production ]

jobs:
  final-production-and-publish:
    runs-on: ubuntu-latest
  
    steps:
      - name: Lint (non-persistent)
        uses: './.github/workflows/reusable/lint.yml'
        with:
          run-linting: true
  
      - name: Format (non-persistent)
        uses: './.github/workflows/reusable/format.yml'
        with:
          persistent: false
  
      - name: Test (non-persistent)
        uses: './.github/workflows/reusable/test.yml'
        with:
          persistent: false
  
      - name: Build (non-persistent)
        uses: './.github/workflows/reusable/build.yml'
        with:
          persistent: false
  
      - name: NPM Publish Dry-Run (non-persistent)
        uses: './.github/workflows/reusable/npm-publish.yml'
        with:
          persistent: false
  
      - name: Format
        uses: './.github/workflows/reusable/format.yml'
        with:
          persistent: true
  
      - name: Test & Coverage
        uses: './.github/workflows/reusable/test.yml'
        with: 
          persistent: true
      
      - name: Build
        uses: './.github/workflows/reusable/build.yml'
        with:
          persistent: true
          
      - name: NPM Publish
        uses: './.github/workflows/reusable/npm-publish.yml'
        with: 
          persistent: true