name: CI Prepare for Production

on:
  pull_request:
    branches: [ production ]

jobs:
  call-lint-non-persistent:
    name: Lint (non-persistent)
    uses: './.github/workflows/reusable.lint.yml'
    with: 
      run-linting: true

  call-format-non-persistent:
    name: Format (non-persistent)
    uses: './.github/workflows/reusable.format.yml'
    with:
      persistent: false

  call-test-non-persistent:
    name: Test (non-persistent)
    uses: './.github/workflows/reusable.test.yml'
    with: 
      persistent: false

  call-build-non-persistent:
    name: Build (non-persistent)
    uses: './.github/workflows/reusable.build.yml'
    with: 
      persistent: false
  
  call-npm-publish-non-persistent:
    name: NPM Publish Dry-Run (non-persistent)
    uses: './.github/workflows/reusable.npm-publish.yml'
    with: 
      persistent: false

  call-format:
    name: Format
    uses: './.github/workflows/reusable.format.yml'
    with:
      persistent: true

  call-build:
    name: Build
    uses: './.github/workflows/reusable.build.yml'
    with: 
      persistent: true