# .github/workflows/ci.yml
name: Nanosplash CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    uses: ./.github/workflows/reusables/bun-build.reusable.yml
    with:
      working-directory: .

  test:
    needs: build
    uses: ./.github/workflows/reusables/bun-test.reusable.yml
    with:
      working-directory: .

  lint:
    needs: build
    uses: ./.github/workflows/reusables/bun-lint.reusable.yml
    with:
      working-directory: .