name: CI

on:
  push:
    branches: [ci]
  pull_request:
    branches: [ci]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Jest (TS) Testing Procedure
        run: |
          yarn install
          yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install npm packages
        run: yarn install

      - name: Transpile Typescript
        run: yarn tsc

      - name: Build IIFE bundle
        run: yarn vite build -c vite.iife.config.js

      - name: Build module bundles
        run: yarn vite build -c vite.mod.config.js

      - name: Build demo site
        run: yarn vite build -c vite.site.config.js

      - name: Build documentation site
        run: yarn typedoc --readme none --excludePrivate --excludeInternal --out docs/typedoc --entryPoints src/Nanosplash.ts src/types.d.ts
