# .github/workflows/ci.yml
name: Nanosplash CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    uses: ./.github/workflows/bun-build.reusable.yml
    with:
      working-directory: .

  test:
    needs: build
    uses: ./.github/workflows/bun-test.reusable.yml
    with:
      working-directory: .
      upload-to-coveralls: true

  lint:
    needs: build
    uses: ./.github/workflows/bun-lint.reusable.yml
    with:
      working-directory: .
