name: Reusable - NPM Publish

on:
  workflow_call:
    inputs:
      persistent:
        required: true
        type: boolean

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      # Checking out the repository with the latest version
      - uses: actions/checkout@v4

      # Setting up the latest Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'  # Specify NPM registry
          
      # Install latest npm
      - name: Install latest npm
        run: npm install -g npm@latest

      # Installing dependencies
      - name: Install Dependencies
        run: npm install --no-package-lock
          
      # Get the version inside package.json
      - name: Get version from package.json
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Publishing to NPM (dry-run for testing purposes)
      - name: Publish to NPM (dry-run)
        run: npm publish --dry-run
          
      # Commit the version tag made by NPM
      - name: Commit version tag
        if: ${{ inputs.persist }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "GitHub Actions: NPM build ${{ env.VERSION }}" --allow-empty
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        if: ${{ inputs.persistent }}
        run: npm publish --provenance --access public